import { formatMoney } from "@/lib/money";
import { AllocationFormDialog } from "@/components/budget/allocation-form-dialog";
import { RemoveAllocationButton } from "@/components/budget/remove-allocation-button";
import { PlanBalance } from "@/components/budget/plan-balance";
import type { AllocationWithActual, AvailableAllocationOption } from "@/lib/budget-allocations";

export function AllocationList({ allocations, budgetPeriodId, currency, availableCategories }: { allocations: AllocationWithActual[]; budgetPeriodId: string; currency: string; availableCategories: AvailableAllocationOption[] }) {
  if (!allocations.length) return <p className="text-muted-foreground">No budget allocations for this cycle yet.</p>;
  return <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[680px] text-sm"><thead className="bg-accent-tint text-muted-foreground"><tr><th scope="col" className="p-3 text-left font-medium">Category</th><th scope="col" className="p-3 text-right font-medium">Planned budget</th><th scope="col" className="p-3 text-right font-medium">Actual spent</th><th scope="col" className="p-3 text-right font-medium">Difference / Remaining</th><th scope="col" className="p-3 text-right font-medium">Actions</th></tr></thead><tbody>{allocations.map((a) => { const label = a.subcategoryName ? `${a.category.name} — ${a.subcategoryName}` : a.category.name; return <tr key={a.id} className="border-t border-border bg-card"><th scope="row" className="p-3 text-left font-medium">{label}{a.rolloverAmount !== 0 && <p className="text-xs font-normal text-muted-foreground">Includes {formatMoney(a.rolloverAmount,currency)} rollover</p>}</th><td className="p-3 text-right tabular-nums">{formatMoney(a.effectivePlanned,currency)}</td><td className="p-3 text-right tabular-nums">{formatMoney(a.actual,currency)}</td><td className="p-3"><PlanBalance planned={a.effectivePlanned} actual={a.actual} currency={currency} kind="spending" /></td><td className="p-3"><div className="flex justify-end gap-2"><AllocationFormDialog budgetPeriodId={budgetPeriodId} currency={currency} availableCategories={availableCategories} existing={a} existingLabel={label} /><RemoveAllocationButton allocationId={a.id} /></div></td></tr>; })}</tbody></table></div>;
}
