"use client";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createCycleIncomePlanAction, deleteCycleIncomePlanAction, updateCycleIncomePlanAction } from "@/actions/cycle-income-plan.actions";
import { formatMoney, toMajorUnits } from "@/lib/money";
import { PlanBalance } from "@/components/budget/plan-balance";

type Row = { id: string; source: string; expectedAmount: number; expectedDate: Date; actual: number; difference: number; actualTransactionId: string | null };
export function CycleIncomePlanTable({ rows, budgetPeriodId, currency }: { rows: Row[]; budgetPeriodId: string; currency: string }) {
  const router = useRouter();
  async function finish(result: { ok: boolean; error?: string }, message: string): Promise<void> { if (!result.ok) { toast.error(result.error); return; } toast.success(message); router.refresh(); }
  return <section className="flex flex-col gap-3"><h2 className="text-sm font-medium text-muted-foreground">Expected income vs actual received</h2><form action={async (fd) => finish(await createCycleIncomePlanAction(fd),"Income plan saved")} className="flex flex-wrap items-end gap-2 rounded-lg border border-border p-3"><input type="hidden" name="budgetPeriodId" value={budgetPeriodId} /><label className="text-sm">Source<input required name="source" className="ml-2 h-9 rounded border px-2" placeholder="Salary" /></label><label className="text-sm">Expected<input required name="expectedAmount" type="number" min="0" step="0.01" className="ml-2 h-9 w-32 rounded border px-2" /></label><label className="text-sm">Date<input required name="expectedDate" type="date" className="ml-2 h-9 rounded border px-2" /></label><button className="h-9 rounded bg-primary px-3 text-sm text-primary-foreground">Add income plan</button></form>
    <p className="text-xs text-muted-foreground">Actual totals Income transactions categorized to this income source in the selected cycle. Receipt names do not need to match.</p>
    {!rows.length ? <p className="text-sm text-muted-foreground">No expected income added for this cycle.</p> : <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[780px] text-sm"><thead className="bg-accent-tint text-muted-foreground"><tr><th scope="col" className="p-3 text-left font-medium">Income source</th><th scope="col" className="p-3 text-left font-medium">Expected date</th><th scope="col" className="p-3 text-right font-medium">Expected</th><th scope="col" className="p-3 text-right font-medium">Actual received</th><th scope="col" className="p-3 text-right font-medium">Difference / Remaining</th><th scope="col" className="p-3 text-right font-medium">Actions</th></tr></thead><tbody>{rows.map((row) => { const formId = `income-${row.id}`; return <tr key={row.id} className="border-t border-border bg-card"><th scope="row" className="p-3 text-left font-medium"><input aria-label="Income source" name="source" form={formId} required defaultValue={row.source} className="h-9 w-40 rounded border px-2" /></th><td className="p-3"><input aria-label="Expected income date" name="expectedDate" form={formId} type="date" required defaultValue={row.expectedDate.toISOString().slice(0,10)} className="h-9 rounded border px-2" /></td><td className="p-3 text-right"><input aria-label="Expected income" name="expectedAmount" form={formId} type="number" step="0.01" min="0" required defaultValue={toMajorUnits(row.expectedAmount,currency)} className="h-9 w-28 rounded border px-2 text-right tabular-nums" /></td><td className="p-3 text-right tabular-nums">{formatMoney(row.actual,currency)}</td><td className="p-3"><PlanBalance planned={row.expectedAmount} actual={row.actual} currency={currency} kind="income" /></td><td className="p-3"><div className="flex justify-end gap-2"><form id={formId} action={async (fd) => finish(await updateCycleIncomePlanAction(row.id,fd),"Income plan updated")}><button className="h-9 rounded border px-3">Save</button></form><button type="button" onClick={async () => finish(await deleteCycleIncomePlanAction(row.id),"Income plan deleted")} className="text-danger underline">Delete</button></div></td></tr>; })}</tbody></table></div>}
  </section>;
}
