"use client";

import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createCycleIncomePlanAction, deleteCycleIncomePlanAction, linkCycleIncomeActualAction, updateCycleIncomePlanAction } from "@/actions/cycle-income-plan.actions";
import { formatMoney, toMajorUnits } from "@/lib/money";
import { Card } from "@/components/ui/card";

type Row = { id: string; source: string; expectedAmount: number; expectedDate: Date; actual: number; difference: number; actualTransactionId: string | null };
type TransactionOption = { id: string; description: string; amount: number; date: Date };
export function CycleIncomePlanTable({ rows, transactions, budgetPeriodId, currency }: { rows: Row[]; transactions: TransactionOption[]; budgetPeriodId: string; currency: string }) {
  const router = useRouter();
  async function finish(result: { ok: boolean; error?: string }, message: string): Promise<void> { if (!result.ok) { toast.error(result.error); return; } toast.success(message); router.refresh(); }
  return <section className="flex flex-col gap-3"><h2 className="text-sm font-medium text-muted-foreground">Expected income vs actual received</h2>
    <Card className="p-4"><form action={async (fd) => finish(await createCycleIncomePlanAction(fd), "Income plan saved")} className="flex flex-wrap items-end gap-2"><input type="hidden" name="budgetPeriodId" value={budgetPeriodId} /><label className="text-sm">Source<input required name="source" className="ml-2 h-9 rounded border px-2" placeholder="Salary" /></label><label className="text-sm">Expected<input required name="expectedAmount" type="number" min="0" step="0.01" className="ml-2 h-9 w-32 rounded border px-2" /></label><label className="text-sm">Date<input required name="expectedDate" type="date" className="ml-2 h-9 rounded border px-2" /></label><button className="h-9 rounded bg-primary px-3 text-sm text-primary-foreground">Add income plan</button></form></Card>
    {rows.length === 0 ? <p className="text-sm text-muted-foreground">No expected income added for this cycle.</p> : <div className="flex flex-col gap-2">{rows.map((row) => <Card key={row.id} className="p-4"><form action={async (fd) => finish(await updateCycleIncomePlanAction(row.id, fd), "Income plan updated")} className="grid gap-3 md:grid-cols-[1fr_140px_140px_140px_auto]"><input name="source" defaultValue={row.source} className="h-9 rounded border px-2" /><input name="expectedAmount" type="number" step="0.01" min="0" defaultValue={toMajorUnits(row.expectedAmount, currency)} className="h-9 rounded border px-2" /><div className="text-sm"><span className="text-muted-foreground">Actual</span><p className="font-medium">{formatMoney(row.actual, currency)}</p></div><div className={`text-sm ${row.difference < 0 ? "text-danger" : ""}`}><span>Difference</span><p className="font-medium">{formatMoney(row.difference, currency)}</p></div><button className="h-9 rounded border px-3 text-sm">Save</button><input name="expectedDate" type="date" defaultValue={row.expectedDate.toISOString().slice(0,10)} className="h-9 rounded border px-2" /></form>
      <div className="mt-3 flex flex-wrap items-center gap-2">{row.actualTransactionId ? <span className="text-sm text-success">Income transaction linked</span> : <form action={async (fd) => finish(await linkCycleIncomeActualAction(row.id, String(fd.get("transactionId"))), "Actual income linked")} className="flex gap-2"><select required name="transactionId" className="h-9 rounded border px-2 text-sm"><option value="">Choose received transaction</option>{transactions.map((t) => <option key={t.id} value={t.id}>{t.description} · {formatMoney(Math.abs(t.amount), currency)} · {t.date.toLocaleDateString()}</option>)}</select><button className="h-9 rounded border px-3 text-sm">Link actual</button></form>}<button onClick={async () => finish(await deleteCycleIncomePlanAction(row.id), "Income plan deleted")} className="text-sm text-danger underline" type="button">Delete</button></div></Card>)}</div>}
  </section>;
}
