"use client";
import {useState,type ReactNode,type ChangeEvent} from "react";
import {applyPlanDrafts,type PlanDraft} from "@/lib/plan-funding";
import {formatMoney,toMinorUnits} from "@/lib/money";
export function PlanFundingWorkspace({opening,expected,allocated,currency,children}:{opening:number;expected:number;allocated:number;currency:string;children:ReactNode}){
 const [drafts,setDrafts]=useState<Record<string,PlanDraft>>({});
 const values=applyPlanDrafts(opening,expected,allocated,Object.values(drafts));
 function update(event:ChangeEvent<HTMLElement>){const target=event.target;if(!(target instanceof HTMLInputElement)||!target.validity.valid)return;const value=Number(target.value);if(!Number.isFinite(value)||value<0)return;const income=target.getAttribute("aria-label")==="Expected income";const key=target.dataset.planKey??(income?target.getAttribute("form"):null);if(!key)return;const kind=income?"income":target.dataset.planKind;if(kind!=="income"&&kind!=="allocation")return;const draft:PlanDraft={kind,base:income?toMinorUnits(Number(target.defaultValue),currency):Number(target.dataset.planBase),value:toMinorUnits(value,currency)};setDrafts(previous=>({...previous,[key]:draft}));}
 const changed=Object.values(drafts).some(d=>d.value!==d.base);
 return <div onChangeCapture={update} className="flex min-w-0 flex-col gap-7"><section className="rounded-xl border bg-card p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-lg font-medium">Money available to budget</h2><span className="text-xs text-muted-foreground">{changed?"Includes unsaved edits":"Saved plan"}</span></div><div className="mt-4 grid grid-cols-2 gap-4 lg:grid-cols-4">{[["Opening spendable funds",opening,"At cycle start"],["Expected income",values.expected,"This cycle · not cash received"],["Total available to budget",values.available,"Opening funds + expected income"],["Already allocated",values.allocated,"Spending + payments + savings"]].map(([label,value,note])=><div key={String(label)}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-medium tabular-nums">{formatMoney(Number(value),currency)}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-2 rounded-lg bg-accent-tint p-4" aria-live="polite"><div><p className="font-medium">{values.remaining<0?"Over budget — reduce planned allocations":"Remaining to budget"}</p><p className="text-xs text-muted-foreground">Not yet assigned · different from current cash or safe to spend</p></div><output data-testid="remaining-to-budget" className={`text-2xl font-medium tabular-nums ${values.remaining<0?"text-danger":"text-success"}`}>{formatMoney(values.remaining,currency)}</output></div><p className="mt-3 text-xs text-muted-foreground">Reserved funds, including ChinaBank, stay separate. Regular bills are part of spending budgets; loan and card payments are additional allocations. Save each row to keep your edits.</p></section>{children}</div>;
}
