"use client";
import {useState} from "react";
import {buildAccountActivity,type ActivityTransaction} from "@/lib/workspace-ledger";
import {formatMoney} from "@/lib/money";
import {TransactionList} from "./transaction-list";
import {EditTransactionButton} from "./edit-transaction-button";
import {DeleteTransactionButton} from "./delete-transaction-button";
import {AuditHistoryLink} from "@/components/audit-log/audit-history-link";
type Account={id:string;name:string;currency:string;accountType:string};
type Category={id:string;name:string;subcategories:{id:string;name:string}[]};
type Transaction=ActivityTransaction&{notes:string|null;categoryId:string|null;subcategoryId:string|null;account:{name:string;currency:string};category:{name:string}|null};
export function AccountActivityTable({transactions,accounts,categories}:{transactions:Transaction[];accounts:Account[];categories:Category[]}){
 const [view,setView]=useState("accounts");const activity=buildAccountActivity(transactions,accounts);const byId=new Map(transactions.map(t=>[t.id,t]));
 return <section className="min-w-0"><div className="mb-4 flex flex-wrap gap-2" role="group" aria-label="Transaction view"><button type="button" aria-pressed={view==="accounts"} onClick={()=>setView("accounts")} className="rounded-lg border px-4 py-2 text-sm aria-pressed:bg-primary aria-pressed:text-primary-foreground">Account columns</button><button type="button" aria-pressed={view==="list"} onClick={()=>setView("list")} className="rounded-lg border px-4 py-2 text-sm aria-pressed:bg-primary aria-pressed:text-primary-foreground">List view</button></div>{view==="list"?<TransactionList transactions={transactions} categories={categories}/>:<><p className="mb-3 text-xs text-muted-foreground">Cash: + received / − sent. Card debt: + charged / − repaid. Scroll across to see all accounts.</p>{!activity.length?<p className="text-muted-foreground">No transactions match these filters.</p>:<div className="max-w-full overflow-x-auto rounded-lg border"><table className="workspace-account-table w-full text-sm"><thead><tr><th>Description</th><th>Date</th><th>Type / status</th><th>Category</th>{accounts.map(a=><th key={a.id} className="min-w-32 text-right">{a.name}{a.accountType==="CREDIT_CARD"&&<span className="block text-xs font-normal">Card debt</span>}</th>)}<th>Actions</th></tr></thead><tbody>{activity.map(row=>{const txn=byId.get(row.id)!;return <tr key={row.id}><th scope="row" className="min-w-48 text-left font-medium">{row.description}</th><td className="whitespace-nowrap">{new Date(row.date).toLocaleDateString("en-PH",{timeZone:"Asia/Manila"})}</td><td className="min-w-40">{row.label}<span className="block text-xs text-muted-foreground">{row.status==="PENDING"?"Pending":"Cleared"}</span></td><td className="min-w-32">{txn.category?.name??"—"}</td>{accounts.map(a=><td key={a.id} className={`whitespace-nowrap text-right tabular-nums ${row.amounts[a.id]===undefined?"text-muted-foreground":row.amounts[a.id]<0?"text-danger":"text-success"}`}>{row.amounts[a.id]===undefined?"—":`${row.amounts[a.id]>0?"+":""}${formatMoney(row.amounts[a.id],a.currency)}`}</td>)}<td><div className="flex gap-2"><AuditHistoryLink entityType="TRANSACTION" entityId={txn.id}/><EditTransactionButton transactionId={txn.id} description={txn.description} notes={txn.notes} categoryId={txn.categoryId} subcategoryId={txn.subcategoryId} categories={categories}/><DeleteTransactionButton transactionId={txn.id}/></div></td></tr>})}</tbody></table></div>}</>}</section>;
}
