"use client";
import {useState,type ReactNode} from "react";
import {Dialog,DialogContent,DialogTitle} from "@/components/ui/dialog";
import {AccountFormDialog} from "./account-form-dialog";
import {ReconcileDialog} from "./reconcile-dialog";
import {formatMoney} from "@/lib/money";
import Link from "next/link";
type Account={id:string;name:string;accountType:string;openingBalance:number;currency:string;purpose:string;isPrimaryFundingAccount:boolean;color:string;icon:string;balance:number;updatedAt:Date;history:{id:string;description:string;date:Date;amount:number}[]};
export function DashboardBalanceVisibility({children}:{children:ReactNode}){const [hidden,setHidden]=useState(false);return <div className={hidden?"dashboard-money-hidden flex flex-col gap-6":"flex flex-col gap-6"}><div className="flex justify-end"><button type="button" aria-pressed={hidden} onClick={()=>setHidden(!hidden)} className="rounded-lg border bg-card px-3 py-2 text-sm">{hidden?"Show account balances":"Hide account balances"}</button></div>{children}</div>}
export function DashboardAccountDetails({accounts}:{accounts:Account[]}){
 const [selected,setSelected]=useState<Account|null>(null);
 return <><details data-account-breakdown className="dashboard-account-breakdown mt-4 border-t pt-3"><summary className="cursor-pointer text-sm text-primary"><span className="when-closed">Show accounts</span><span className="when-open">Hide accounts</span></summary><div className="mt-3 flex flex-col gap-2">{accounts.map(a=><button type="button" key={a.id} onClick={()=>setSelected(a)} className="flex flex-wrap items-center justify-between gap-2 rounded-md px-1 py-2 text-left text-sm hover:bg-accent"><span>{a.name}</span><span className="dashboard-balance tabular-nums">{formatMoney(a.balance,a.currency)}</span></button>)}{!accounts.length&&<p className="text-xs text-muted-foreground">No accounts in this group yet.</p>}</div></details><Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="inset-y-0 left-auto right-0 top-0 h-full max-h-full w-[440px] max-w-[95vw] translate-x-0 translate-y-0 rounded-none sm:max-w-[440px]">{selected&&<><DialogTitle>{selected.name}</DialogTitle><div><p className="text-xs text-muted-foreground">Current balance</p><p className="dashboard-balance mt-1 text-2xl font-medium">{formatMoney(selected.balance,selected.currency)}</p><p className="mt-2 text-xs text-muted-foreground">Account last updated {new Date(selected.updatedAt).toLocaleDateString("en-PH",{timeZone:"Asia/Manila"})}</p></div><div className="flex flex-wrap gap-2"><AccountFormDialog existing={selected}/><ReconcileDialog accountId={selected.id} currency={selected.currency}/></div><h2 className="font-medium">Recent activity</h2><div className="flex flex-col gap-3">{selected.history.map(t=><div key={t.id} className="flex justify-between gap-3 border-b pb-3"><div><p>{t.description}</p><p className="text-xs text-muted-foreground">{new Date(t.date).toLocaleDateString("en-PH",{timeZone:"Asia/Manila"})}</p></div><p className="whitespace-nowrap tabular-nums">{formatMoney(t.amount,selected.currency)}</p></div>)}</div><Link href={`/transactions?accountId=${selected.id}`} className="text-primary underline">View all activity or record a transfer</Link></>}</DialogContent></Dialog></>;
}
