import Link from "next/link";
import {auth} from "@/auth";
import {prisma} from "@/lib/prisma";
import {formatMoney} from "@/lib/money";
import {computeAccountBalance} from "@/lib/account-balance";
import {ClearReservedPaymentDialog} from "@/components/bills/clear-reserved-payment-dialog";
import {PayableFormDialog} from "@/components/bills/payable-form-dialog";
import {RecurringPayableFormDialog} from "@/components/bills/recurring-payable-form-dialog";
export default async function TierraAltaPage(){
 const session=await auth();const userId=session!.user.id;
 const [accounts,categories]=await Promise.all([prisma.account.findMany({where:{userId,archivedAt:null},orderBy:{createdAt:"asc"}}),prisma.category.findMany({where:{userId,archivedAt:null}})]);
 const reserves=accounts.filter(a=>a.purpose==="RESTRICTED");
 const sections=await Promise.all(reserves.map(async account=>{const [balance,payables,transactions]=await Promise.all([computeAccountBalance(prisma,account.id),prisma.payable.findMany({where:{userId,accountId:account.id},orderBy:{dueDate:"asc"}}),prisma.transaction.findMany({where:{userId,accountId:account.id,type:"EXPENSE",status:"CLEARED",amount:{lt:0}},orderBy:{date:"desc"}})]);return {account,balance,payables,transactions}}));
 return <div className="flex flex-col gap-6"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-xl font-semibold">Tierra Alta</h1><p className="mt-1 text-sm text-muted-foreground">Reserve funding, pending cheques and cleared payments</p></div><div className="flex flex-wrap gap-2"><PayableFormDialog accounts={reserves} categories={categories}/><RecurringPayableFormDialog accounts={reserves} categories={categories}/></div></div>{!sections.length&&<p className="text-muted-foreground">Set an account’s purpose to dedicated reserve to track its funding here.</p>}{sections.map(({account,balance,payables,transactions})=>{const pending=payables.filter(p=>p.status==="PENDING");const committed=pending.reduce((s,p)=>s+p.amount,0);return <section key={account.id} className="rounded-xl border bg-card p-4 sm:p-5"><h2 className="text-lg font-medium">{account.name} · Reserved mainly for Tierra Alta</h2><div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-3">{[["Account balance",balance],["Pending cheque commitments",committed],["Reserve after commitments",balance-committed]].map(([label,value])=><div key={String(label)}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-medium tabular-nums">{formatMoney(Number(value),account.currency)}</p></div>)}</div><p className="mt-4 text-xs text-muted-foreground">Deposits carry forward. Transfers are not expenses. Emergency withdrawals remain available and reduce the reserve.</p><Link className="mt-3 inline-block text-sm text-primary underline" href={`/transactions?accountId=${account.id}`}>View activity, add funds or transfer money out</Link><div className="mt-5 overflow-x-auto rounded-lg border"><table className="w-full min-w-[690px] text-sm"><thead><tr>{["Payment / cheque","Due date","Amount","Status","Action"].map(label=><th key={label} className="p-3 text-left font-medium">{label}</th>)}</tr></thead><tbody>{payables.map(p=><tr key={p.id} className="border-t"><th scope="row" className="p-3 text-left font-medium">{p.name}</th><td className="p-3">{p.dueDate.toLocaleDateString("en-PH",{timeZone:"Asia/Manila"})}{!p.dueDateConfirmed&&<span className="block text-xs text-muted-foreground">Estimated</span>}</td><td className="p-3 tabular-nums">{formatMoney(p.amount,account.currency)}</td><td className="p-3">{p.status==="PAID"?"Cleared & paid":"Pending · not yet deducted"}</td><td className="p-3">{p.status==="PENDING"?<ClearReservedPaymentDialog id={p.id} name={p.name} amount={p.amount} currency={account.currency} accountName={account.name} matches={transactions.filter(t=>t.amount===-p.amount&&!payables.some(other=>other.paidTransactionId===t.id))}/>:"Recorded"}</td></tr>)}</tbody></table></div>{!payables.length&&<p className="mt-3 text-sm text-muted-foreground">No saved cheque commitments. Add a payment or recurring schedule above.</p>}</section>})}</div>;
}
