import Link from "next/link";
import { PaymentPlanForm } from "@/components/bills/payment-plan-form";
import { PlanBalance } from "@/components/budget/plan-balance";
import { formatMoney } from "@/lib/money";
import type { MonthlyObligationRow } from "@/lib/monthly-obligations";

export function MonthlyObligationsSection({ title, rows, periodId }: { title: string; rows: MonthlyObligationRow[]; periodId: string }) {
  return <section><h2 className="mb-3 text-sm font-medium text-muted-foreground">{title}</h2>{!rows.length ? <p className="text-sm text-muted-foreground">Nothing scheduled for this cycle.</p> : <div className="overflow-x-auto rounded-lg border border-border"><table className="w-full min-w-[820px] text-sm"><thead className="bg-accent-tint text-muted-foreground"><tr><th scope="col" className="p-3 text-left font-medium">Item</th><th scope="col" className="p-3 text-left font-medium">Due date</th><th scope="col" className="p-3 text-right font-medium">Planned payment</th><th scope="col" className="p-3 text-right font-medium">Actual paid</th><th scope="col" className="p-3 text-right font-medium">Difference / Remaining</th><th scope="col" className="p-3 text-right font-medium">Actions</th></tr></thead><tbody>{rows.map((item) => { const canPlan = item.sourceType === "LOAN" || item.sourceType === "CREDIT_CARD"; return <tr key={item.id} className="border-t border-border bg-card"><th scope="row" className="p-3 text-left font-medium">{item.name}<p className="text-xs font-normal text-muted-foreground">{item.status.toLowerCase()}</p></th><td className="whitespace-nowrap p-3 text-muted-foreground">{item.dueDate?.toLocaleDateString() ?? "Not set"}</td><td className="p-3 text-right tabular-nums">{canPlan ? <PaymentPlanForm periodId={periodId} sourceType={item.sourceType as "LOAN" | "CREDIT_CARD"} sourceId={item.sourceId} dueDate={item.dueDate?.toISOString().slice(0,10) ?? new Date().toISOString().slice(0,10)} expected={item.expected} compact /> : formatMoney(item.expected,item.currency)}</td><td className="p-3 text-right tabular-nums">{formatMoney(item.actual,item.currency)}</td><td className="p-3"><PlanBalance planned={item.expected} actual={item.actual} currency={item.currency} kind="payment" /></td><td className="p-3 text-right">{canPlan && <Link className="whitespace-nowrap text-primary underline" href="/loans-cards">Record payment</Link>}</td></tr>; })}</tbody></table></div>}</section>;
}
